version: "3.8"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./auth:/auth
      - ./data:/var/lib/registry

  ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    environment:
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: "Secure Docker Registry"
      REGISTRY_URL: "https://13.38.244.45:443"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
    depends_on:
      - registry

  nginx:
    image: nginx:alpine
    container_name: registry-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - registry
      - ui