---
- name: Déploiement d'un registre Docker sécurisé
  hosts: registry_hosts
  become: true
  vars:
    project_dir: "/home/ubuntu/registry-stack"
    # Récupère l'IP publique automatiquement via les facts ansible
    public_ip: "{{ ansible_host }}"
  
  tasks:

    ######################
    # 1. INSTALLATION DES DEPENDANCES
    ########################
    - name: Mise a jour du cache API
      apt:
        update_cache: yes

    - name: Installation de docker et outils
      apt:
        name:
          - docker.io 
          - docker-compose-v2
          - apache2-utils
          - python3-passlib
          - openssl
        state: present

    - name: Ajout de l'utilisateur ubuntu au group docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Création des dossiers
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

      loop:
        - "{{ project_dir }}"
        - "{{ project_dir }}/auth"
        - "{{ project_dir }}/data"
        - "{{ project_dir }}/ssl"
        - "{{ project_dir }}/conf"

    - name: copie du openssl conf
      template:
        src: openssl-san.cnf
        dest: "{{ project_dir }}/ssl/openssl-san.cnf"
        owner: ubuntu
        group: ubuntu
        mode: '0644'  

    - name: Génération du certificat SSL auto-signé
      command: >
        openssl req -newkey rsa:4096 -nodes -sha256
        -keyout {{ project_dir }}/ssl/registry.key
        -x509 -days 365
        -out {{ project_dir }}/ssl/registry.crt
        -config ssl/openssl-san.cnf 
        -subj "/CN={{ public_ip }}"

      args:
        chdir: "{{ project_dir }}"
      become: true

    - name: Génération mot de passe (admin/admin123)
      htpasswd:
        path: "{{ project_dir }}/auth/registry.password"
        name: admin
        password: admin123
        owner: ubuntu
        group: ubuntu
        mode: 0640
        crypt_scheme: bcrypt


    - name: copie du nginx.conf
      template:
        src: nginx.conf
        dest: "{{ project_dir }}/conf/nginx.conf"
        owner: ubuntu
        group: ubuntu
        mode: '0644'   

    - name: Copie du docker-compose.yml
      template:
        src: docker-compose.yml
        dest: "{{ project_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Démarrage de la stack
      command: docker compose up -d
      args:
        chdir: "{{ project_dir }}"