name: Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - arnaud-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Step 1 - Build Docker Frontend
        run: docker build -t frontend-test -f react.Dockerfile .

      - name: Step 1 bis - Build Docker API
        run: docker build -t api-test ./api

      - name: Step 2 - Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Step 2 bis - Terraform Init
        run: |
          cd terraform/app
          terraform init

      - name: Step 2 ter - Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform/app
          terraform apply -auto-approve

      - name: Step 3 - Get IP and SSH Key
        run: |
          cd terraform/app
          echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
          terraform output -raw private_key_pem > private_key.pem
          chmod 600 private_key.pem

      - name: Step 3.5 - Generate .env file
        run: |
          echo "REACT_APP_SERVER_PORT=8000" >> .env
          echo "REACT_APP_API_URL=http://$PUBLIC_IP:8000" >> .env
          echo "MYSQL_DATABASE=users" >> .env
          echo "MYSQL_ROOT_PASSWORD=ynov-CICD" >> .env

      - name: Step 3.6 - Generate inventory.ini
        run: |
          echo "[app_hosts]" > ansible/inventory.ini
          echo "$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/app/private_key.pem" >> ansible/inventory.ini

      - name: Step 4 - Run Ansible Playbook
        run: |
          cd ansible
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini playbook-app.yml