name: Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - arnaud-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Step 1 - Build Docker Frontend
        run: docker build -t frontend-test -f react.Dockerfile .

      - name: Step 1 bis - Build Docker API
        run: docker build -t api-test ./api

      - name: Step 2 - Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Step 2 bis - Terraform Init
        run: |
          cd terraform/app
          terraform init

      - name: Step 3 - Bridge Terraform -> Ansible
        run: echo "Récupération IP et clé SSH depuis Terraform"

      - name: Step 4 - Ansible Deployment
        run: echo "Déploiement avec Ansible"