name: Docker Compose Integration

on:
  push:
    branches: [ main ]

jobs:

  docker-compose-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=root" >> .env
          echo "REACT_APP_SERVER_PORT=8000" >> .env

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 30

      - name: Test API
        run: |
          RESPONSE=$(curl -s http://localhost:8000/users)
          echo "$RESPONSE"

          echo "$RESPONSE" | grep utilisateurs

      - name: Test Frontend
        run: |
          curl -f http://localhost:3000 || exit 1

      - name: Stop containers
        run: docker compose down